# Form implementation generated from reading ui file '.\ConnectDialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 226)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.filePathLabel = QtWidgets.QLabel(parent=Dialog)
        self.filePathLabel.setObjectName("filePathLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.filePathLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filePathLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.filePathLineEdit.setText("")
        self.filePathLineEdit.setObjectName("filePathLineEdit")
        self.horizontalLayout_2.addWidget(self.filePathLineEdit)
        self.browseButton = QtWidgets.QPushButton(parent=Dialog)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_2.addWidget(self.browseButton)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_2)
        self.materialLabel = QtWidgets.QLabel(parent=Dialog)
        self.materialLabel.setObjectName("materialLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.materialLabel)
        self.materialLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.materialLineEdit.setObjectName("materialLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.materialLineEdit)
        self.temperatureLabel = QtWidgets.QLabel(parent=Dialog)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.temperatureLabel)
        self.temperatureLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.temperatureLineEdit.setObjectName("temperatureLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.temperatureLineEdit)
        self.volumeLabel = QtWidgets.QLabel(parent=Dialog)
        self.volumeLabel.setObjectName("volumeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.volumeLabel)
        self.volumeLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.volumeLineEdit.setObjectName("volumeLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.volumeLineEdit)
        self.currentLabel = QtWidgets.QLabel(parent=Dialog)
        self.currentLabel.setObjectName("currentLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.currentLabel)
        self.currentLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.currentLineEdit.setObjectName("currentLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.currentLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.filePathLabel.setText(_translate("Dialog", "Output Directory"))
        self.browseButton.setText(_translate("Dialog", "Browse..."))
        self.materialLabel.setText(_translate("Dialog", "Material"))
        self.temperatureLabel.setText(_translate("Dialog", "Temperature"))
        self.volumeLabel.setText(_translate("Dialog", "Volume"))
        self.currentLabel.setText(_translate("Dialog", "Current"))
